/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradletest;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int n=10;
        int fac=1;
        for(int i=1;i<n;i++){
            
            fac*=i;
            System.out.println("Factorial of "+i+": "+fac);
        }
    }
}
